# render.yaml
services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "streamlit run app.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
